export const BILLING_TAX_ID_TYPES = {
    ad_nrt: "Andorra NRT",
    ae_trn: "UAE tax registration number",
    al_tin: "Albania TIN",
    am_tin: "Armenia TIN",
    ao_tin: "Angola TIN",
    ar_cuit: "Argentina CUIT",
    au_abn: "Australia ABN",
    au_arn: "Australia ARN",
    aw_tin: "Aruba TIN",
    az_tin: "Azerbaijan TIN",
    ba_tin: "Bosnia and Herzegovina TIN",
    bb_tin: "Barbados TIN",
    bd_bin: "Bangladesh BIN",
    bf_ifu: "Burkina Faso IFU",
    bg_uic: "Bulgaria UIC",
    bh_vat: "Bahrain VAT",
    bj_ifu: "Benin IFU",
    bo_tin: "Bolivia TIN",
    br_cnpj: "Brazil CNPJ",
    br_cpf: "Brazil CPF",
    bs_tin: "Bahamas TIN",
    by_tin: "Belarus TIN",
    ca_bn: "Canada business number",
    ca_gst_hst: "Canada GST/HST",
    ca_pst_bc: "British Columbia PST",
    ca_pst_mb: "Manitoba PST",
    ca_pst_sk: "Saskatchewan PST",
    ca_qst: "Quebec QST",
    cd_nif: "DR Congo NIF",
    ch_uid: "Switzerland UID",
    ch_vat: "Switzerland VAT",
    cl_tin: "Chile TIN",
    cm_niu: "Cameroon NIU",
    cn_tin: "China TIN",
    co_nit: "Colombia NIT",
    cr_tin: "Costa Rica TIN",
    cv_nif: "Cape Verde NIF",
    de_stn: "Germany tax number",
    do_rcn: "Dominican Republic RCN",
    ec_ruc: "Ecuador RUC",
    eg_tin: "Egypt TIN",
    es_cif: "Spain CIF",
    et_tin: "Ethiopia TIN",
    eu_vat: "EU VAT",
    gb_vat: "United Kingdom VAT",
    ge_vat: "Georgia VAT",
    gn_nif: "Guinea NIF",
    hk_br: "Hong Kong BR",
    hr_oib: "Croatia OIB",
    hu_tin: "Hungary TIN",
    id_npwp: "Indonesia NPWP",
    il_vat: "Israel VAT",
    in_gst: "India GST",
    is_vat: "Iceland VAT",
    jp_cn: "Japan corporate number",
    jp_rn: "Japan registered number",
    jp_trn: "Japan tax registration number",
    ke_pin: "Kenya PIN",
    kg_tin: "Kyrgyzstan TIN",
    kh_tin: "Cambodia TIN",
    kr_brn: "South Korea BRN",
    kz_bin: "Kazakhstan BIN",
    la_tin: "Laos TIN",
    li_uid: "Liechtenstein UID",
    li_vat: "Liechtenstein VAT",
    lk_vat: "Sri Lanka VAT",
    ma_vat: "Morocco VAT",
    md_vat: "Moldova VAT",
    me_pib: "Montenegro PIB",
    mk_vat: "North Macedonia VAT",
    mr_nif: "Mauritania NIF",
    mx_rfc: "Mexico RFC",
    my_frp: "Malaysia FRP",
    my_itn: "Malaysia ITN",
    my_sst: "Malaysia SST",
    ng_tin: "Nigeria TIN",
    no_vat: "Norway VAT",
    no_voec: "Norway VOEC",
    np_pan: "Nepal PAN",
    nz_gst: "New Zealand GST",
    om_vat: "Oman VAT",
    pe_ruc: "Peru RUC",
    ph_tin: "Philippines TIN",
    pl_nip: "Poland NIP",
    ro_tin: "Romania TIN",
    rs_pib: "Serbia PIB",
    ru_inn: "Russia INN",
    ru_kpp: "Russia KPP",
    sa_vat: "Saudi Arabia VAT",
    sg_gst: "Singapore GST",
    sg_uen: "Singapore UEN",
    si_tin: "Slovenia TIN",
    sn_ninea: "Senegal NINEA",
    sr_fin: "Suriname FIN",
    sv_nit: "El Salvador NIT",
    th_vat: "Thailand VAT",
    tj_tin: "Tajikistan TIN",
    tr_tin: "Turkey TIN",
    tw_vat: "Taiwan VAT",
    tz_vat: "Tanzania VAT",
    ua_vat: "Ukraine VAT",
    ug_tin: "Uganda TIN",
    us_ein: "United States EIN",
    uy_ruc: "Uruguay RUC",
    uz_tin: "Uzbekistan TIN",
    uz_vat: "Uzbekistan VAT",
    ve_rif: "Venezuela RIF",
    vn_tin: "Vietnam TIN",
    za_vat: "South Africa VAT",
    zm_tin: "Zambia TIN",
    zw_tin: "Zimbabwe TIN",
} as const;

export type BillingTaxIdType = keyof typeof BILLING_TAX_ID_TYPES;

const EU_VAT_COUNTRIES = new Set([
    "AT", "BE", "CY", "CZ", "DK", "EE", "FI", "FR", "GR", "IE", "IT",
    "LT", "LU", "LV", "MT", "NL", "PT", "SE", "SK",
]);

const COUNTRY_TAX_ID_TYPES: Partial<Record<string, readonly BillingTaxIdType[]>> = {
    AD: ["ad_nrt"], AE: ["ae_trn"], AL: ["al_tin"], AM: ["am_tin"], AO: ["ao_tin"],
    AR: ["ar_cuit"], AU: ["au_abn", "au_arn"], AW: ["aw_tin"], AZ: ["az_tin"],
    BA: ["ba_tin"], BB: ["bb_tin"], BD: ["bd_bin"], BF: ["bf_ifu"],
    BG: ["bg_uic", "eu_vat"], BH: ["bh_vat"], BJ: ["bj_ifu"], BO: ["bo_tin"],
    BR: ["br_cnpj", "br_cpf"], BS: ["bs_tin"], BY: ["by_tin"],
    CA: ["ca_bn", "ca_gst_hst", "ca_pst_bc", "ca_pst_mb", "ca_pst_sk", "ca_qst"],
    CD: ["cd_nif"], CH: ["ch_uid", "ch_vat"], CL: ["cl_tin"], CM: ["cm_niu"],
    CN: ["cn_tin"], CO: ["co_nit"], CR: ["cr_tin"], CV: ["cv_nif"],
    DE: ["de_stn", "eu_vat"], DO: ["do_rcn"], EC: ["ec_ruc"], EG: ["eg_tin"],
    ES: ["es_cif", "eu_vat"], ET: ["et_tin"], GB: ["gb_vat"], GE: ["ge_vat"],
    GN: ["gn_nif"], HK: ["hk_br"], HR: ["hr_oib", "eu_vat"],
    HU: ["hu_tin", "eu_vat"], ID: ["id_npwp"], IL: ["il_vat"], IN: ["in_gst"],
    IS: ["is_vat"], JP: ["jp_cn", "jp_rn", "jp_trn"], KE: ["ke_pin"],
    KG: ["kg_tin"], KH: ["kh_tin"], KR: ["kr_brn"], KZ: ["kz_bin"],
    LA: ["la_tin"], LI: ["li_uid", "li_vat"], LK: ["lk_vat"], MA: ["ma_vat"],
    MD: ["md_vat"], ME: ["me_pib"], MK: ["mk_vat"], MR: ["mr_nif"],
    MX: ["mx_rfc"], MY: ["my_frp", "my_itn", "my_sst"], NG: ["ng_tin"],
    NO: ["no_vat", "no_voec"], NP: ["np_pan"], NZ: ["nz_gst"], OM: ["om_vat"],
    PE: ["pe_ruc"], PH: ["ph_tin"], PL: ["pl_nip", "eu_vat"],
    RO: ["ro_tin", "eu_vat"], RS: ["rs_pib"], RU: ["ru_inn", "ru_kpp"],
    SA: ["sa_vat"], SG: ["sg_gst", "sg_uen"], SI: ["si_tin", "eu_vat"],
    SN: ["sn_ninea"], SR: ["sr_fin"], SV: ["sv_nit"], TH: ["th_vat"],
    TJ: ["tj_tin"], TR: ["tr_tin"], TW: ["tw_vat"], TZ: ["tz_vat"],
    UA: ["ua_vat"], UG: ["ug_tin"], US: ["us_ein"], UY: ["uy_ruc"],
    UZ: ["uz_tin", "uz_vat"], VE: ["ve_rif"], VN: ["vn_tin"],
    ZA: ["za_vat"], ZM: ["zm_tin"], ZW: ["zw_tin"],
};

export function isBillingTaxIdType(value: string): value is BillingTaxIdType {
    return Object.prototype.hasOwnProperty.call(BILLING_TAX_ID_TYPES, value);
}

export function getBillingTaxIdOptions(country: string): ReadonlyArray<{
    value: BillingTaxIdType;
    label: string;
}> {
    const normalizedCountry = country.trim().toUpperCase();
    const types = COUNTRY_TAX_ID_TYPES[normalizedCountry]
        ?? (EU_VAT_COUNTRIES.has(normalizedCountry) ? ["eu_vat"] : []);

    return types.map((value) => ({ value, label: BILLING_TAX_ID_TYPES[value] }));
}
