-- Durable crawl frontier for Cencori's shared public corpus and future
-- asynchronous project crawls. All mutation functions are service-role only.

CREATE TABLE IF NOT EXISTS public.web_crawl_jobs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    collection_id text NOT NULL DEFAULT 'public',
    visibility text NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'project')),
    organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
    project_id uuid REFERENCES public.projects(id) ON DELETE CASCADE,
    seeds jsonb NOT NULL DEFAULT '[]'::jsonb,
    allowed_origins text[] NOT NULL DEFAULT '{}',
    same_origin boolean NOT NULL DEFAULT true,
    max_pages integer NOT NULL DEFAULT 1000 CHECK (max_pages BETWEEN 1 AND 1000000),
    max_frontier integer NOT NULL DEFAULT 20000 CHECK (max_frontier BETWEEN 1 AND 5000000),
    max_depth integer NOT NULL DEFAULT 2 CHECK (max_depth BETWEEN 0 AND 10),
    max_attempts integer NOT NULL DEFAULT 3 CHECK (max_attempts BETWEEN 1 AND 10),
    priority smallint NOT NULL DEFAULT 0 CHECK (priority BETWEEN -100 AND 100),
    status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'completed', 'failed', 'cancelled')),
    pages_discovered integer NOT NULL DEFAULT 0,
    items_processed integer NOT NULL DEFAULT 0,
    pages_processed integer NOT NULL DEFAULT 0,
    pages_indexed integer NOT NULL DEFAULT 0,
    pages_failed integer NOT NULL DEFAULT 0,
    pages_skipped integer NOT NULL DEFAULT 0,
    worker_id text,
    lease_expires_at timestamptz,
    last_error text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT web_crawl_jobs_scope_check CHECK (
        (visibility = 'public' AND collection_id = 'public' AND organization_id IS NULL AND project_id IS NULL)
        OR
        (visibility = 'project' AND organization_id IS NOT NULL AND project_id IS NOT NULL AND collection_id = 'project:' || project_id::text)
    )
);

CREATE TABLE IF NOT EXISTS public.web_crawl_frontier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id uuid NOT NULL REFERENCES public.web_crawl_jobs(id) ON DELETE CASCADE,
    url text NOT NULL,
    origin text NOT NULL,
    parent_url text,
    depth integer NOT NULL DEFAULT 0 CHECK (depth BETWEEN 0 AND 32),
    kind text NOT NULL DEFAULT 'page' CHECK (kind IN ('page', 'sitemap')),
    status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'leased', 'completed', 'failed', 'skipped')),
    attempts integer NOT NULL DEFAULT 0,
    available_at timestamptz NOT NULL DEFAULT now(),
    worker_id text,
    lease_expires_at timestamptz,
    document_id uuid REFERENCES public.web_documents(id) ON DELETE SET NULL,
    last_error text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT web_crawl_frontier_job_url_key UNIQUE (job_id, url)
);

CREATE INDEX IF NOT EXISTS web_crawl_jobs_claim_idx
    ON public.web_crawl_jobs(priority DESC, created_at)
    WHERE status IN ('queued', 'running');
CREATE INDEX IF NOT EXISTS web_crawl_jobs_lease_idx
    ON public.web_crawl_jobs(lease_expires_at)
    WHERE status = 'running';
CREATE INDEX IF NOT EXISTS web_crawl_frontier_claim_idx
    ON public.web_crawl_frontier(job_id, status, available_at, depth, id);
CREATE INDEX IF NOT EXISTS web_crawl_frontier_lease_idx
    ON public.web_crawl_frontier(lease_expires_at)
    WHERE status = 'leased';

ALTER TABLE public.web_crawl_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.web_crawl_frontier ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Organization members can read project crawl jobs"
    ON public.web_crawl_jobs FOR SELECT
    USING (
        visibility = 'project'
        AND EXISTS (
            SELECT 1
            FROM public.organization_members om
            WHERE om.organization_id = web_crawl_jobs.organization_id
              AND om.user_id = auth.uid()
        )
    );

CREATE POLICY "Organization members can read project crawl frontier"
    ON public.web_crawl_frontier FOR SELECT
    USING (
        EXISTS (
            SELECT 1
            FROM public.web_crawl_jobs j
            JOIN public.organization_members om ON om.organization_id = j.organization_id
            WHERE j.id = web_crawl_frontier.job_id
              AND j.visibility = 'project'
              AND om.user_id = auth.uid()
        )
    );

CREATE OR REPLACE FUNCTION public.enqueue_web_crawl_urls(
    p_job_id uuid,
    p_entries jsonb
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_job public.web_crawl_jobs%ROWTYPE;
    v_inserted integer := 0;
    v_remaining integer;
BEGIN
    SELECT * INTO v_job
    FROM public.web_crawl_jobs
    WHERE id = p_job_id
      AND status IN ('queued', 'running')
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'crawl job is not active';
    END IF;

    v_remaining := GREATEST(v_job.max_frontier - v_job.pages_discovered, 0);
    IF v_remaining = 0 OR jsonb_typeof(p_entries) <> 'array' THEN
        RETURN 0;
    END IF;

    INSERT INTO public.web_crawl_frontier (
        job_id, url, origin, parent_url, depth, kind, metadata
    )
    SELECT
        p_job_id,
        e.url,
        e.origin,
        NULLIF(e.parent_url, ''),
        GREATEST(0, LEAST(e.depth, 32)),
        CASE WHEN e.kind = 'sitemap' THEN 'sitemap' ELSE 'page' END,
        COALESCE(e.metadata, '{}'::jsonb)
    FROM jsonb_to_recordset(p_entries) AS e(
        url text,
        origin text,
        parent_url text,
        depth integer,
        kind text,
        metadata jsonb
    )
    WHERE e.url ~ '^https?://'
      AND e.origin ~ '^https?://'
      AND (
          NOT v_job.same_origin
          OR e.origin = ANY(v_job.allowed_origins)
      )
      AND (
          e.kind = 'sitemap'
          OR GREATEST(0, e.depth) <= v_job.max_depth
      )
    ORDER BY CASE WHEN e.kind = 'sitemap' THEN 0 ELSE 1 END, e.depth, e.url
    LIMIT v_remaining
    ON CONFLICT (job_id, url) DO NOTHING;

    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    UPDATE public.web_crawl_jobs
    SET pages_discovered = pages_discovered + v_inserted,
        updated_at = now()
    WHERE id = p_job_id;

    RETURN v_inserted;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_web_crawl_batch(
    p_worker_id text,
    p_limit integer DEFAULT 5,
    p_lease_seconds integer DEFAULT 60
)
RETURNS TABLE (
    job_id uuid,
    frontier_id bigint,
    url text,
    origin text,
    parent_url text,
    depth integer,
    kind text,
    attempts integer,
    max_depth integer,
    max_attempts integer,
    same_origin boolean,
    allowed_origins text[],
    max_pages integer,
    max_frontier integer,
    visibility text,
    collection_id text,
    organization_id uuid,
    project_id uuid
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_job public.web_crawl_jobs%ROWTYPE;
    v_limit integer := LEAST(GREATEST(p_limit, 1), 25);
    v_lease_seconds integer := LEAST(GREATEST(p_lease_seconds, 15), 300);
    v_remaining_pages integer;
BEGIN
    -- A worker may have crashed after consuming the page budget but before
    -- releasing its job. Close those jobs and discard their unclaimed tail.
    WITH exhausted AS (
        SELECT j.id,
               (SELECT count(*)::integer
                FROM public.web_crawl_frontier f
                WHERE f.job_id = j.id AND f.status IN ('queued', 'leased') AND f.kind = 'page') AS skipped_count
        FROM public.web_crawl_jobs j
        WHERE j.status IN ('queued', 'running')
          AND j.pages_processed >= j.max_pages
          AND (j.lease_expires_at IS NULL OR j.lease_expires_at <= now())
    ), skipped AS (
        UPDATE public.web_crawl_frontier f
        SET status = 'skipped',
            worker_id = NULL,
            lease_expires_at = NULL,
            last_error = 'page_budget_exhausted',
            updated_at = now()
        FROM exhausted e
        WHERE f.job_id = e.id AND f.status IN ('queued', 'leased')
        RETURNING f.job_id
    )
    UPDATE public.web_crawl_jobs j
    SET status = 'completed',
        pages_skipped = pages_skipped + e.skipped_count,
        worker_id = NULL,
        lease_expires_at = NULL,
        finished_at = COALESCE(finished_at, now()),
        updated_at = now()
    FROM exhausted e
    WHERE j.id = e.id;

    SELECT j.* INTO v_job
    FROM public.web_crawl_jobs j
    WHERE j.status IN ('queued', 'running')
      AND j.pages_processed < j.max_pages
      AND (j.lease_expires_at IS NULL OR j.lease_expires_at <= now())
      AND EXISTS (
          SELECT 1
          FROM public.web_crawl_frontier f
          WHERE f.job_id = j.id
            AND (
                (f.status = 'queued' AND f.available_at <= now())
                OR (f.status = 'leased' AND f.lease_expires_at <= now())
            )
      )
    ORDER BY j.priority DESC, j.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    UPDATE public.web_crawl_jobs
    SET status = 'running',
        worker_id = p_worker_id,
        lease_expires_at = now() + make_interval(secs => v_lease_seconds),
        started_at = COALESCE(started_at, now()),
        updated_at = now()
    WHERE id = v_job.id;

    v_remaining_pages := GREATEST(v_job.max_pages - v_job.pages_processed, 0);

    RETURN QUERY
    WITH ranked AS (
        SELECT
            f.id,
            f.kind,
            sum(CASE WHEN f.kind = 'page' THEN 1 ELSE 0 END)
                OVER (ORDER BY CASE WHEN f.kind = 'sitemap' THEN 0 ELSE 1 END, f.depth, f.id) AS page_rank
        FROM public.web_crawl_frontier f
        WHERE f.job_id = v_job.id
          AND (
              (f.status = 'queued' AND f.available_at <= now())
              OR (f.status = 'leased' AND f.lease_expires_at <= now())
          )
    ), eligible AS (
        SELECT r.id
        FROM ranked r
        WHERE r.kind = 'sitemap' OR r.page_rank <= v_remaining_pages
        ORDER BY CASE WHEN r.kind = 'sitemap' THEN 0 ELSE 1 END, r.id
        LIMIT v_limit
    ), claimed AS (
        UPDATE public.web_crawl_frontier f
        SET status = 'leased',
            attempts = f.attempts + 1,
            worker_id = p_worker_id,
            lease_expires_at = now() + make_interval(secs => v_lease_seconds),
            updated_at = now()
        FROM eligible e
        WHERE f.id = e.id
        RETURNING f.*
    )
    SELECT
        v_job.id,
        c.id,
        c.url,
        c.origin,
        c.parent_url,
        c.depth,
        c.kind,
        c.attempts,
        v_job.max_depth,
        v_job.max_attempts,
        v_job.same_origin,
        v_job.allowed_origins,
        v_job.max_pages,
        v_job.max_frontier,
        v_job.visibility,
        v_job.collection_id,
        v_job.organization_id,
        v_job.project_id
    FROM claimed c
    ORDER BY CASE WHEN c.kind = 'sitemap' THEN 0 ELSE 1 END, c.depth, c.id;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_web_crawl_item(
    p_job_id uuid,
    p_frontier_id bigint,
    p_worker_id text,
    p_status text,
    p_document_id uuid DEFAULT NULL,
    p_error text DEFAULT NULL,
    p_retry boolean DEFAULT false,
    p_retry_delay_seconds integer DEFAULT 60
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_item public.web_crawl_frontier%ROWTYPE;
    v_max_attempts integer;
BEGIN
    IF p_status NOT IN ('completed', 'failed', 'skipped') THEN
        RAISE EXCEPTION 'invalid crawl item status';
    END IF;

    SELECT f.* INTO v_item
    FROM public.web_crawl_frontier f
    WHERE f.id = p_frontier_id
      AND f.job_id = p_job_id
      AND f.status = 'leased'
      AND f.worker_id = p_worker_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN false;
    END IF;

    SELECT max_attempts INTO v_max_attempts
    FROM public.web_crawl_jobs
    WHERE id = p_job_id;

    IF p_retry AND v_item.attempts < v_max_attempts THEN
        UPDATE public.web_crawl_frontier
        SET status = 'queued',
            available_at = now() + make_interval(secs => LEAST(GREATEST(p_retry_delay_seconds, 1), 86400)),
            worker_id = NULL,
            lease_expires_at = NULL,
            last_error = left(p_error, 4000),
            updated_at = now()
        WHERE id = p_frontier_id;

        UPDATE public.web_crawl_jobs
        SET last_error = left(p_error, 4000), updated_at = now()
        WHERE id = p_job_id;
        RETURN true;
    END IF;

    UPDATE public.web_crawl_frontier
    SET status = p_status,
        document_id = p_document_id,
        worker_id = NULL,
        lease_expires_at = NULL,
        last_error = left(p_error, 4000),
        updated_at = now()
    WHERE id = p_frontier_id;

    UPDATE public.web_crawl_jobs
    SET items_processed = items_processed + 1,
        pages_processed = pages_processed + CASE WHEN v_item.kind = 'page' THEN 1 ELSE 0 END,
        pages_indexed = pages_indexed + CASE WHEN v_item.kind = 'page' AND p_document_id IS NOT NULL THEN 1 ELSE 0 END,
        pages_failed = pages_failed + CASE WHEN v_item.kind = 'page' AND p_status = 'failed' THEN 1 ELSE 0 END,
        pages_skipped = pages_skipped + CASE WHEN v_item.kind = 'page' AND p_status = 'skipped' THEN 1 ELSE 0 END,
        last_error = CASE WHEN p_status = 'failed' THEN left(p_error, 4000) ELSE last_error END,
        updated_at = now()
    WHERE id = p_job_id;
    RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.release_web_crawl_job(
    p_job_id uuid,
    p_worker_id text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_job public.web_crawl_jobs%ROWTYPE;
    v_skipped integer := 0;
    v_remaining integer := 0;
    v_status text;
BEGIN
    SELECT * INTO v_job
    FROM public.web_crawl_jobs
    WHERE id = p_job_id AND worker_id = p_worker_id
    FOR UPDATE;
    IF NOT FOUND THEN RETURN 'not_owned'; END IF;

    IF v_job.pages_processed >= v_job.max_pages THEN
        SELECT count(*)::integer INTO v_skipped
        FROM public.web_crawl_frontier
        WHERE job_id = p_job_id AND status IN ('queued', 'leased') AND kind = 'page';

        UPDATE public.web_crawl_frontier
        SET status = 'skipped',
            worker_id = NULL,
            lease_expires_at = NULL,
            last_error = 'page_budget_exhausted',
            updated_at = now()
        WHERE job_id = p_job_id AND status IN ('queued', 'leased');
    END IF;

    SELECT count(*)::integer INTO v_remaining
    FROM public.web_crawl_frontier
    WHERE job_id = p_job_id AND status IN ('queued', 'leased');

    v_status := CASE WHEN v_remaining = 0 THEN 'completed' ELSE 'queued' END;
    UPDATE public.web_crawl_jobs
    SET status = v_status,
        pages_skipped = pages_skipped + v_skipped,
        worker_id = NULL,
        lease_expires_at = NULL,
        finished_at = CASE WHEN v_status = 'completed' THEN COALESCE(finished_at, now()) ELSE NULL END,
        updated_at = now()
    WHERE id = p_job_id;
    RETURN v_status;
END;
$$;

REVOKE ALL ON FUNCTION public.enqueue_web_crawl_urls(uuid, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.claim_web_crawl_batch(text, integer, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.complete_web_crawl_item(uuid, bigint, text, text, uuid, text, boolean, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.release_web_crawl_job(uuid, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.enqueue_web_crawl_urls(uuid, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_web_crawl_batch(text, integer, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_web_crawl_item(uuid, bigint, text, text, uuid, text, boolean, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_web_crawl_job(uuid, text) TO service_role;
